[Feature] Runtime Mappings
babenkoivan/elastic-adapter pull request #30
Opened 2022-06-08 07:21 UTC by stefnats

2022-06-08 07:31 UTC, stefnats commented
When this is merged, `elastic-scout-driver-plus` can be merged to support this as well. I admit, it is difficult to develop for multiple depending repositories.

2022-08-17 06:04 UTC, babenkoivan requested changes

2022-08-17 06:04 UTC, babenkoivan commented on tests/Unit/Search/SearchRequestTest.php
> +    public function test_array_casting_with_runtime_mapping(): void
```suggestion
    public function test_array_casting_with_runtime_mappings(): void
```

2022-08-17 06:04 UTC, babenkoivan commented on tests/Unit/Search/SearchRequestTest.php
> +        $request = new SearchRequest([
```suggestion
        $request = new SearchRequest();
```

2022-08-17 06:04 UTC, babenkoivan commented on tests/Unit/Search/SearchRequestTest.php
> +        $this->assertEquals([
```suggestion

        $this->assertEquals([
```

2022-08-17 06:15 UTC, babenkoivan commented
Hey @stefnats, thanks for the PR! I've made some suggestions (all are small things related to the code style). 
Could you please also resolve merge conflicts and add usage examples in README?

2022-09-24 01:15 UTC, closed without merging